/*DROPPING ALL CONTRAINTS*/

ALTER TABLE MATRIX.SKILLS
DROP FOREIGN KEY FK_DIV_SKILL;

ALTER TABLE MATRIX.ROLES
DROP FOREIGN KEY FK_DIV_ROLE;

ALTER TABLE MATRIX.B_EMPLOYEE_ROLES
DROP FOREIGN KEY FK_EMP_ROLE, 
DROP FOREIGN KEY FK_ROLE;

ALTER TABLE MATRIX.B_EMPLOYEE_SKILLS
DROP FOREIGN KEY FK_EMP_SKILL, 
DROP FOREIGN KEY  FK_SKILL, 
DROP FOREIGN KEY  FK_LEVEL;


/*DROPPING ALL TABLES*/
DROP TABLE IF EXISTS MATRIX.USERS;
DROP TABLE IF EXISTS MATRIX.EMPLOYEES;
DROP TABLE IF EXISTS MATRIX.SKILLS;
DROP TABLE IF EXISTS MATRIX.DIVISIONS;
DROP TABLE IF EXISTS MATRIX.M_SKILLS_LEVEL;
DROP TABLE IF EXISTS MATRIX.B_EMPLOYEE_SKILLS;
DROP TABLE IF EXISTS MATRIX.ROLES;
DROP TABLE IF EXISTS MATRIX.B_EMPLOYEE_ROLES;


DROP SCHEMA IF EXISTS MATRIX;
CREATE SCHEMA MATRIX;



CREATE TABLE MATRIX.USERS
(EMAIL VARCHAR(60) PRIMARY KEY,
PASS VARCHAR(60) NOT NULL);

CREATE TABLE MATRIX.EMPLOYEES
(EMP_ID INT AUTO_INCREMENT PRIMARY KEY,
NAMES VARCHAR(60) NOT NULL,
SHORE VARCHAR(20) NOT NULL);

CREATE TABLE MATRIX.DIVISIONS
(DIVISION_ID INT AUTO_INCREMENT PRIMARY KEY,
 DIV_DESCRIPTION VARCHAR(60) NOT NULL);

CREATE TABLE MATRIX.SKILLS
(SKILL_ID INT AUTO_INCREMENT PRIMARY KEY, 
SKILL_DESCRIPTION VARCHAR(60) NOT NULL,
DIVISION_ID INT NOT NULL);

CREATE TABLE MATRIX.M_SKILLS_LEVEL
(LEVEL_ID INT AUTO_INCREMENT PRIMARY KEY,
LEVEL_DESCR VARCHAR(30) NOT NULL);

CREATE TABLE MATRIX.B_EMPLOYEE_SKILLS
(EMPLOYEE_ID INT NOT NULL,
SKILL_ID INT NOT NULL,
LEVEL_ID INT NOT NULL,
PRIMARY KEY (EMPLOYEE_ID, SKILL_ID));

CREATE TABLE MATRIX.ROLES
(ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
 ROLE_DESCRIPTION VARCHAR(60) NOT NULL,
 DIVISION_ID INT NOT NULL);
 
CREATE TABLE MATRIX.B_EMPLOYEE_ROLES
(EMPLOYEE_ID INT NOT NULL,
 ROLE_ID INT NOT NULL,
 PRIMARY KEY (EMPLOYEE_ID, ROLE_ID));
 
 
/* ADDING CONTRAINTS

-- FOR SKILLS TABLE*/
ALTER TABLE MATRIX.SKILLS
ADD CONSTRAINT FK_DIV_SKILL
FOREIGN KEY (DIVISION_ID) 
REFERENCES MATRIX.DIVISIONS(DIVISION_ID);

/* FOR ROLES TABLE*/
ALTER TABLE MATRIX.ROLES
ADD CONSTRAINT FK_DIV_ROLE
FOREIGN KEY (DIVISION_ID) 
REFERENCES MATRIX.DIVISIONS(DIVISION_ID);

/* FOR EMPLOYEE ROLE BRIDGE*/
ALTER TABLE MATRIX.B_EMPLOYEE_ROLES
ADD CONSTRAINT FK_EMP_ROLE
FOREIGN KEY (EMPLOYEE_ID) 
REFERENCES MATRIX.EMPLOYEES(EMP_ID),
ADD CONSTRAINT FK_ROLE
FOREIGN KEY (ROLE_ID)
REFERENCES MATRIX.ROLES(ROLE_ID);

/* FOR EMPLOYEE SKILLS BRIDGE*/
ALTER TABLE MATRIX.B_EMPLOYEE_SKILLS
ADD CONSTRAINT FK_EMP_SKILL
FOREIGN KEY (EMPLOYEE_ID) 
REFERENCES MATRIX.EMPLOYEES(EMP_ID),
ADD CONSTRAINT FK_SKILL
FOREIGN KEY (SKILL_ID)
REFERENCES MATRIX.SKILLS(SKILL_ID),
ADD CONSTRAINT FK_LEVEL 
FOREIGN KEY (LEVEL_ID)
REFERENCES MATRIX.M_SKILLS_LEVEL(LEVEL_ID);


